# https://taskfile.dev

version: "3"

tasks:
  run:
    desc: "Run the cli"
    cmd: uv run main.py {{.CLI_ARGS}}

  sync:
    desc: "Install dependencies"
    cmd: uv sync --dev

  check:
    desc: "Lint files"
    cmd: uv run ruff check .

  format:
    desc: "Format files"
    cmd: uv run ruff format .
